functional:
  - Пользователь может пройти регистрацию на сайте.
  - Пользователь может зарегистрироваться на сайте только имея существующую электронную почту.
  - Пользователь может войти в систему, используя учетную запись GitHub.
  - Пользователь может войти в систему, используя учетную запись Discord.
  - Пользователь может авторизоваться в системе используя логин и пароль.
  - Пользователь может восстановить пароль.
  - Пользователь может запустить игру без входа в систему.
  - Пользователь может изменить электронную почту, пароль, аватар, в настройках профиля. 
  - Пользователь может выйти из профиля.
  - Пользователь может менять язык программирования в настройках профиля из доступных (clojure, cpp, csharp, dart, elixir, go, haskell, java, javascript, kotlin, php, python, ruby, rust, typescript).
  - Пользователь может изменять звуки сайта на dendy/cs/standart/silent.
  - Пользователь может просматривать статистику своего профиля.
  - Пользователь может изменять громкость звука в настройках профиля.
  - Пользователь может просматривать информацию о созданном им турнире.
  - Пользователь может сортировать рейтинг пользователей по недельному, месячному и общему рейтингу
  - Пользователь может создать игру с другим пользователем или ботом.
  - Незарегистрированный пользователь может просматривать историю своей игры с ботом.
  - Зарегистрированный и незарегистрированный пользователь может просматривать Guide в игре с ботом.
  - В игровом поле пользователю доступен выбор темы игры light/dark.
  - У пользователя должна быть возможность сдаться во время игры.
  - Пользователь может обнулить solution. 
  - Пользователь может запустить проверку solution.
  - Пользователю доступен чат с соперником во время игры.
  - После победы/поражения в игре, возможно сделать Rematch игры с настройками предыдущей, с тем же противником.
  - Победа присуждается первому правильно решившему задачу пользователю.
  - Во время игры пользователю доступно для просмотра игровое поле противника, на нем отображаются все действия пользователя.
  - Пользователь может отменить игру до ее начала.
  - Пользователь должен получать очки за победу в играх и они должны отображаться корректно.
  - Показатели рейтинга нового игрока должны быть корректны.
  - Пользователь может использовать приватный чат с игроками online.
  - На главной странице должно отражаться количество игроков online.
  - Количество игроков онлайн должно обновляться при входе/выходе других пользователей на сайт.
  - На главной странице должен быть общий чат со всеми доступными игроками online.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования.
  - Сайт должен быть доступнен на мобильном устройстве.
  - Сайт должен быть совместим с последними версиями браузеров Google Chrome, Mozilla, Safari.
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей).
  - Сайт должен быть безопасным и защищать данные пользователя.
implicit:
  - Все элементы навигационной системы сайта должны быть в рабочем состоянии для беспрепятственного серфинга по сайту
  - Все графические элементы сайта должны быть выполнены в едином стиле на разных страницах сайта
  - На сайте должна присутствовать возможность общения между пользователями (чат в матче, общий чат, приватный чат)
  

