functional:
  - Пользователь может пройти регистрацию на сайте.
  - Пользователь может зарегистрироваться на сайте только имея существующую электронную почту.
  - Пользователь может войти в систему, используя учетную запись GitHub.
  - Пользователь может войти в систему, используя учетную запись Discord.
  - Пользователь может авторизоваться в системе используя логин и пароль.
  - Пользователь может восстановить пароль.
  - Пользователь может запустить игру без входа в систему.
  - Пользователь может изменить электронную почту, пароль, аватар, в настройках профиля. 
  - Пользователь может выйти из профиля.
  - Пользователь может менять язык программирования в настройках профиля из доступных (clojure, cpp, csharp, dart, elixir, go, haskell, java, javascript, kotlin, php, python, ruby, rust, typescript).
  - Пользователь может изменять звуки сайта на dendy/cs/standart/silent.
  - Пользователь может просматривать статистику своего профиля.
  - Пользователь может изменять громкость звука в настройках профиля.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров google chrome, opera, mozilla, yandex.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Все элементы навигационной системы сайта должны быть в рабочем состоянии для беспрепятственного серфинга на сайте
  - Элементы интерфейса сайта должны быть выполнены в современных стилях 
  - Все графические элементы сайта должны быть выполнены в едином стиле и должны быть переиспользованы по возможности на разных страницах сайта
  - На сайте должна присутствовать возможность общения между пользователями (чаты в матче, общий чат, приватный чат)

